# Generated by Django 5.2.6 on 2025-10-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='view_permissions',
            field=models.CharField(choices=[('members', 'Members Only'), ('public', 'Public (Login Required)')], default='members', help_text='Who can view this event? Members = organization members only, Public = any logged-in user', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Deprecated: Use view_permissions instead'),
        ),
    ]
