# Generated by Django 5.2.6 on 2025-10-15 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Message content', max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('user', models.ForeignKey(blank=True, help_text='User who sent the message (null for anonymous users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='messaging_m_timesta_bd3028_idx')],
            },
        ),
    ]
