# Generated by Django 5.2.6 on 2025-10-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo/avatar', null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
