# Generated by Django 5.2.6 on 2025-10-10 15:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, help_text='User must be between 12 and 110 years old', null=True, validators=[accounts.models.validate_age], verbose_name='Date of Birth'),
        ),
    ]
