# Generated by Django 5.2.6 on 2025-10-16 16:16

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number (international format supported, e.g., +1 555-555-5555)', max_length=128, region=None),
        ),
    ]
