# Generated by Django 5.2.6 on 2025-10-19 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('member', 'Member')], default='member', help_text='Permission level determines what actions user can perform', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect')], default='active', help_text='Membership status', max_length=20)),
                ('join_date', models.DateField(auto_now_add=True, help_text='Date user joined organization')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('membership_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Annual membership fee (if applicable)', max_digits=10, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership',
                'ordering': ['organization', 'user'],
            },
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('athlete', 'Athlete/Cyclist'), ('coach', 'Coach'), ('parent', 'Parent'), ('guardian', 'Guardian'), ('team_captain', 'Team Captain'), ('medical_staff', 'Medical Staff'), ('mechanic', 'Mechanic'), ('volunteer', 'Volunteer'), ('official', 'Official'), ('spectator', 'Spectator')], help_text='Type of organizational role (descriptive, not permission)', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary role for display purposes (only one should be primary)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(help_text='Membership this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='membership.membership')),
            ],
            options={
                'verbose_name': 'Member Role',
                'verbose_name_plural': 'Member Roles',
                'ordering': ['-is_primary', 'role_type'],
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='membership_user_id_e06d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'status'], name='membership_organiz_bbf206_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='memberrole',
            unique_together={('membership', 'role_type')},
        ),
    ]
