# Generated by Django 5.2.6 on 2025-10-11 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OrgOwner', 'Organization Owner'), ('OrgAdmin', 'Organization Administrator'), ('OrgManager', 'Organization Manager'), ('OrgCoach', 'Organization Coach'), ('OrgMember', 'Organization Member'), ('OrgParent', 'Organization Parent')], default='OrgMember', help_text='Role within the organization', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect')], default='active', help_text='Membership status', max_length=20)),
                ('join_date', models.DateField(auto_now_add=True, help_text='Date user joined organization')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('membership_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Annual membership fee (if applicable)', max_digits=10, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership',
                'ordering': ['organization', 'user'],
                'indexes': [models.Index(fields=['user', 'status'], name='membership_user_id_e06d3e_idx'), models.Index(fields=['organization', 'status'], name='membership_organiz_bbf206_idx')],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
