# Generated by Django 5.2.6 on 2025-10-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='List of role types (parent, coach_level_1, coach_level_2, coach_level_3, student, guest)'),
        ),
    ]
