# Generated by Django 5.2.6 on 2025-10-12 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='permission_level',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('member', 'Member')], default='member', help_text='Permission level determines what actions user can perform', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OrgOwner', 'Organization Owner'), ('OrgAdmin', 'Organization Administrator'), ('OrgManager', 'Organization Manager'), ('OrgCoach', 'Organization Coach'), ('OrgMember', 'Organization Member'), ('OrgParent', 'Organization Parent')], default='OrgMember', help_text='DEPRECATED: Use permission_level instead', max_length=20),
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('athlete', 'Athlete/Cyclist'), ('coach', 'Coach'), ('parent', 'Parent'), ('guardian', 'Guardian'), ('team_captain', 'Team Captain'), ('medical_staff', 'Medical Staff'), ('mechanic', 'Mechanic'), ('volunteer', 'Volunteer'), ('official', 'Official'), ('spectator', 'Spectator')], help_text='Type of organizational role (descriptive, not permission)', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary role for display purposes (only one should be primary)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(help_text='Membership this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='membership.membership')),
            ],
            options={
                'verbose_name': 'Member Role',
                'verbose_name_plural': 'Member Roles',
                'ordering': ['-is_primary', 'role_type'],
                'unique_together': {('membership', 'role_type')},
            },
        ),
    ]
