# Generated by Django 5.2.6 on 2025-10-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('organization', 'user')},
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect'), ('expired', 'Expired')], default='active', help_text='Membership status', max_length=20),
        ),
    ]
