# Generated by Django 5.2.6 on 2025-10-12 03:07

from django.db import migrations


def migrate_role_to_permission_level(apps, schema_editor):
    """
    Migrate old 'role' field data to new 'permission_level' field
    and create MemberRole entries for coach and parent roles.

    Mapping:
    - OrgOwner → owner
    - OrgAdmin → admin
    - OrgManager → manager
    - OrgCoach → manager + MemberRole(coach)
    - OrgMember → member
    - OrgParent → member + MemberRole(parent)
    """
    Membership = apps.get_model('membership', 'Membership')
    MemberRole = apps.get_model('membership', 'MemberRole')

    # Mapping from old role to new permission_level
    role_to_permission = {
        'OrgOwner': 'owner',
        'OrgAdmin': 'admin',
        'OrgManager': 'manager',
        'OrgCoach': 'manager',  # Coaches get manager permissions
        'OrgMember': 'member',
        'OrgParent': 'member',  # Parents get member permissions
    }

    # Roles that should get a MemberRole entry
    role_to_member_role = {
        'OrgCoach': 'coach',
        'OrgParent': 'parent',
    }

    for membership in Membership.objects.all():
        old_role = membership.role

        # Set permission_level based on old role
        if old_role in role_to_permission:
            membership.permission_level = role_to_permission[old_role]
            membership.save(update_fields=['permission_level'])

            # Create MemberRole if applicable
            if old_role in role_to_member_role:
                MemberRole.objects.get_or_create(
                    membership=membership,
                    role_type=role_to_member_role[old_role],
                    defaults={'is_primary': True}
                )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: convert permission_level back to role.
    Note: This may lose information if users have multiple roles.
    """
    Membership = apps.get_model('membership', 'Membership')
    MemberRole = apps.get_model('membership', 'MemberRole')

    # Reverse mapping
    permission_to_role = {
        'owner': 'OrgOwner',
        'admin': 'OrgAdmin',
        'manager': 'OrgManager',
        'member': 'OrgMember',
    }

    for membership in Membership.objects.all():
        permission_level = membership.permission_level

        # Check if they have a coach or parent role
        has_coach = MemberRole.objects.filter(membership=membership, role_type='coach').exists()
        has_parent = MemberRole.objects.filter(membership=membership, role_type='parent').exists()

        if has_coach:
            membership.role = 'OrgCoach'
        elif has_parent:
            membership.role = 'OrgParent'
        elif permission_level in permission_to_role:
            membership.role = permission_to_role[permission_level]
        else:
            membership.role = 'OrgMember'  # Default

        membership.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_add_permission_level_and_member_roles'),
    ]

    operations = [
        migrations.RunPython(migrate_role_to_permission_level, reverse_migration),
    ]
