# Generated by Django 5.2.6 on 2025-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_options_alter_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='role_type',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('athlete', 'Athlete/Cyclist'), ('coach', 'Coach'), ('parent/guardian', 'Parent/Guardian'), ('team_captain', 'Team Captain'), ('medical_staff', 'Medical Staff'), ('mechanic', 'Mechanic'), ('volunteer', 'Volunteer'), ('official', 'Official'), ('spectator', 'Spectator')], help_text='Type of organizational role (descriptive, not permission)', max_length=20),
        ),
    ]
