# Generated by Django 5.2.6 on 2025-11-01 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_memberrole_role_type'),
        ('organizations', '0005_leagueprofile_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect'), ('expired', 'Expired'), ('pending_renewal', 'Pending Renewal')], default='active', help_text='Membership status', max_length=20),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Season name (e.g., 'Fall 2024', 'Spring 2025')", max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly season identifier', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Season description and details')),
                ('start_date', models.DateField(help_text='Season start date')),
                ('end_date', models.DateField(help_text='Season end date')),
                ('registration_open_date', models.DateField(help_text='When registration opens for this season')),
                ('registration_close_date', models.DateField(blank=True, help_text='When registration closes (leave blank for no deadline)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current active season? (Only one active season per org)')),
                ('is_published', models.BooleanField(default=False, help_text='Is this season visible and accepting registrations?')),
                ('default_membership_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Default membership fee for this season', max_digits=10, null=True)),
                ('max_members', models.PositiveIntegerField(blank=True, help_text='Maximum number of members for this season (blank = unlimited)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Organization this season belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('inactive', 'Inactive'), ('waitlist', 'Waitlist'), ('withdrew', 'Withdrew')], default='registered', help_text='Status for this specific season', max_length=20)),
                ('season_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Membership fee for this season (overrides season default if set)', max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', help_text="Payment status for this season's fee", max_length=20)),
                ('registered_date', models.DateField(auto_now_add=True, help_text='When user registered for this season')),
                ('notes', models.TextField(blank=True, help_text='Season-specific notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(help_text='Base membership record (org-level)', on_delete=django.db.models.deletion.CASCADE, related_name='season_memberships', to='membership.membership')),
                ('season', models.ForeignKey(help_text='Season this participation applies to', on_delete=django.db.models.deletion.CASCADE, related_name='season_memberships', to='membership.season')),
            ],
            options={
                'verbose_name': 'Season Membership',
                'verbose_name_plural': 'Season Memberships',
                'ordering': ['-season__start_date', 'membership__user__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['organization', 'is_active'], name='membership__organiz_cdab58_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['organization', 'start_date', 'end_date'], name='membership__organiz_67c2da_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['is_published', 'registration_open_date'], name='membership__is_publ_cd8a2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='seasonmembership',
            index=models.Index(fields=['season', 'status'], name='membership__season__c5bb69_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonmembership',
            index=models.Index(fields=['membership', 'season'], name='membership__members_fd692c_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonmembership',
            index=models.Index(fields=['season', 'payment_status'], name='membership__season__386fb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonmembership',
            unique_together={('membership', 'season')},
        ),
    ]
