# Generated by Django 5.2.6 on 2025-11-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_membership_status_season_seasonmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='auto_approve_registration',
            field=models.BooleanField(default=True, help_text='Automatically approve season registrations without admin review'),
        ),
        migrations.AddField(
            model_name='season',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text="Instructions for payment (e.g., 'Mail check to...', 'Venmo @username', etc.)"),
        ),
    ]
