# Generated by Django 5.2.6 on 2025-10-23 16:01

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_organization_membership_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sponsor name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the sponsor')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Primary phone number', max_length=128, region=None)),
                ('url', models.URLField(blank=True, help_text='Website URL')),
                ('email', models.EmailField(blank=True, help_text='General contact email', max_length=254)),
                ('contact_name', models.CharField(blank=True, help_text='Contact person name', max_length=200)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact person email', max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact person phone', max_length=128, region=None)),
                ('logo', models.ImageField(blank=True, help_text='Sponsor logo', null=True, upload_to='sponsors/logos/')),
                ('banner_image', models.ImageField(blank=True, help_text='Optional banner image', null=True, upload_to='sponsors/banners/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Active sponsors are publicly visible', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this sponsor is associated with (leave blank for global sponsors)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='organizations.organization')),
                ('owner', models.ForeignKey(help_text='User who created this sponsor', on_delete=django.db.models.deletion.CASCADE, related_name='owned_sponsors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='sponsors_sp_status_9f476d_idx'), models.Index(fields=['organization'], name='sponsors_sp_organiz_c8df26_idx'), models.Index(fields=['owner'], name='sponsors_sp_owner_i_935dcb_idx')],
            },
        ),
    ]
