# Generated by Django 5.2.6 on 2025-10-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='city',
            field=models.CharField(blank=True, help_text='City or location', max_length=100),
        ),
    ]
