# Generated by Django 5.2.6 on 2025-10-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('league', 'League'), ('team', 'Team'), ('squad', 'Squad'), ('club', 'Club')], help_text='Type of organization', max_length=20)),
                ('name', models.CharField(help_text='Organization name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Organization description')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone', max_length=20)),
                ('logo', models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='organizations/logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Is organization active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent organization in hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeagueProfile',
            fields=[
                ('organization', models.OneToOneField(limit_choices_to={'type': 'league'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='league_profile', serialize=False, to='organizations.organization')),
                ('sanctioning_body', models.CharField(blank=True, help_text='Official sanctioning body (e.g., USA Cycling, UCI)', max_length=200)),
                ('region', models.CharField(blank=True, help_text='Geographic region or state', max_length=100)),
                ('membership_requirements', models.TextField(blank=True, help_text='Requirements for league membership')),
            ],
            options={
                'verbose_name': 'League Profile',
                'verbose_name_plural': 'League Profiles',
            },
        ),
        migrations.CreateModel(
            name='SquadProfile',
            fields=[
                ('organization', models.OneToOneField(limit_choices_to={'type': 'squad'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='squad_profile', serialize=False, to='organizations.organization')),
                ('focus_area', models.CharField(choices=[('sprint', 'Sprint'), ('endurance', 'Endurance'), ('climbing', 'Climbing'), ('time_trial', 'Time Trial'), ('track', 'Track'), ('mountain', 'Mountain Biking'), ('youth', 'Youth Development'), ('womens', "Women's Squad")], help_text='Primary focus area for this squad', max_length=20)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite')], default='intermediate', help_text='Target skill level', max_length=20)),
            ],
            options={
                'verbose_name': 'Squad Profile',
                'verbose_name_plural': 'Squad Profiles',
            },
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('organization', models.OneToOneField(limit_choices_to={'type': 'team'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='team_profile', serialize=False, to='organizations.organization')),
                ('race_category', models.CharField(choices=[('cat1', 'Category 1'), ('cat2', 'Category 2'), ('cat3', 'Category 3'), ('cat4', 'Category 4'), ('cat5', 'Category 5'), ('junior', 'Junior'), ('masters', 'Masters'), ('recreational', 'Recreational')], default='recreational', help_text='Primary race category', max_length=20)),
                ('team_colors', models.CharField(blank=True, help_text="Team colors (e.g., 'Blue and White')", max_length=100)),
                ('season_start', models.DateField(blank=True, help_text='Season start date', null=True)),
                ('season_end', models.DateField(blank=True, help_text='Season end date', null=True)),
                ('meeting_location', models.CharField(blank=True, help_text='Regular meeting or training location', max_length=200)),
            ],
            options={
                'verbose_name': 'Team Profile',
                'verbose_name_plural': 'Team Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['type'], name='organizatio_type_7447c3_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_048085_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['parent'], name='organizatio_parent__c2cd70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('parent', 'slug')},
        ),
    ]
