# Generated by Django 5.2.6 on 2025-10-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('league', 'League'), ('team', 'Team'), ('squad', 'Squad'), ('club', 'Club'), ('practice_group', 'Practice Group')], help_text='Type of organization', max_length=20),
        ),
    ]
