# Generated by Django 5.2.6 on 2025-10-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='membership_open',
            field=models.BooleanField(default=True, help_text='Allow new members to join this organization'),
        ),
    ]
