# Generated by Django 5.2.6 on 2025-10-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamprofile',
            name='race_category',
        ),
    ]
