# Generated by Django 5.2.6 on 2025-10-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_race_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadprofile',
            name='focus_area',
        ),
        migrations.RemoveField(
            model_name='squadprofile',
            name='skill_level',
        ),
    ]
