# Generated by Django 5.2.6 on 2025-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_membership_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueprofile',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner image displayed at the top of the league page', null=True, upload_to='organizations/banners/'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner image displayed at the top of the team page', null=True, upload_to='organizations/banners/'),
        ),
    ]
