# Generated by Django 5.2.6 on 2025-10-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_squad_focus_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='team_type',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('racing', 'Racing'), ('devo', 'Devo')], help_text='Type of team', max_length=20),
        ),
    ]
