# Generated by Django 5.2.6 on 2025-10-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_leagueprofile_banner_teamprofile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueprofile',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for display on cards (200 characters max)', max_length=200),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for display on cards (200 characters max)', max_length=200),
        ),
    ]
