# Generated by Django 5.2.6 on 2025-11-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_leagueprofile_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('strava', 'Strava'), ('twitter', 'Twitter / X'), ('bluesky', 'Bluesky'), ('youtube', 'YouTube')], help_text='Social media platform', max_length=20)),
                ('username', models.CharField(help_text='Username or handle (e.g., @teamname)', max_length=100)),
                ('profile_url', models.URLField(help_text='Full URL to the social media profile', max_length=500)),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying accounts (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this account publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Organization this social account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Social Media Account',
                'verbose_name_plural': 'Social Media Accounts',
                'ordering': ['display_order', 'platform'],
                'unique_together': {('organization', 'platform', 'username')},
            },
        ),
    ]
