# Generated by Django 5.2.6 on 2025-10-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_team_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamprofile',
            name='meeting_location',
        ),
        migrations.RemoveField(
            model_name='teamprofile',
            name='season_end',
        ),
        migrations.RemoveField(
            model_name='teamprofile',
            name='season_start',
        ),
        migrations.RemoveField(
            model_name='teamprofile',
            name='team_colors',
        ),
    ]
