# Generated by Django 5.2.6 on 2025-11-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_socialmediaaccount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('organization', 'profile_url')},
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='username',
            field=models.CharField(blank=True, help_text='Username or handle (e.g., @teamname). Optional for platforms like Strava.', max_length=100),
        ),
    ]
